/**
 * Extension CRUD.
 *
 * Every query filters on `organizationId` from the tenant middleware. That is the isolation
 * boundary — there is no Postgres RLS behind it, so a missing filter here is a data leak.
 *
 * Every mutation does three things beyond the database write: audit, refresh the Redis cache
 * Lua reads, and project the SIP credential into Kamailio's subscriber table. Skipping any one
 * of them leaves the system internally inconsistent in a way that is hard to diagnose later.
 */
import { randomUUID } from "node:crypto";
import { Hono } from "hono";
import { and, eq } from "drizzle-orm";
import { db } from "../db";
import { extension, tenantSettings } from "../db/schema";
import { encrypt, generateSipPassword, generateVoicemailPin } from "../lib/crypto";
import { recordAudit } from "../lib/audit";
import { cacheExtension, invalidateExtension } from "../services/cache";
import { syncSubscriber, removeSubscriber } from "../services/kamailio-sync";
import { requireTenant, type AppEnv } from "../middleware/tenant";

export const extensions = new Hono<AppEnv>();
extensions.use("*", requireTenant);

/** The SIP password is never returned, on any route. It leaves the API only as an HA1 digest. */
function present(row: typeof extension.$inferSelect) {
  const { sipPasswordEnc: _p, voicemailPinEnc: _v, ...safe } = row;
  return safe;
}

extensions.get("/", async (c) => {
  const rows = await db.query.extension.findMany({
    where: eq(extension.organizationId, c.get("organizationId")),
    orderBy: (t, { asc }) => [asc(t.number)],
  });
  return c.json(rows.map(present));
});

extensions.get("/:id", async (c) => {
  const row = await db.query.extension.findFirst({
    where: and(
      eq(extension.id, c.req.param("id")),
      eq(extension.organizationId, c.get("organizationId")),
    ),
  });
  if (!row) return c.json({ error: "Not found" }, 404);
  return c.json(present(row));
});

extensions.post("/", async (c) => {
  const organizationId = c.get("organizationId");
  const body = await c.req.json<{
    number?: string;
    displayName?: string;
    sipPassword?: string;
    voicemailEnabled?: boolean;
    voicemailPin?: string;
    voicemailEmail?: string;
    callerIdName?: string;
    callerIdNumber?: string;
    codecPrefs?: string;
    maxConcurrentCalls?: number;
    deviceMac?: string;
  }>();

  if (!body.number || !body.displayName) {
    return c.json({ error: "number and displayName are required" }, 400);
  }

  const tenant = await db.query.tenantSettings.findFirst({
    where: eq(tenantSettings.organizationId, organizationId),
  });
  if (!tenant) return c.json({ error: "Tenant is not provisioned" }, 409);

  const existing = await db.query.extension.findFirst({
    where: and(
      eq(extension.organizationId, organizationId),
      eq(extension.number, body.number),
    ),
  });
  if (existing) return c.json({ error: `Extension ${body.number} already exists` }, 409);

  // Generated by default: an operator-chosen SIP password is a common source of toll fraud.
  const password = body.sipPassword ?? generateSipPassword();
  //[ Always set, even with voicemail disabled: it can be turned on later, and a mailbox that
  //  exists without a PIN falls back to the SIP password, which nobody can dial. ]
  const pin = body.voicemailPin ?? generateVoicemailPin();

  const [row] = await db
    .insert(extension)
    .values({
      id: randomUUID(),
      organizationId,
      number: body.number,
      displayName: body.displayName,
      sipPasswordEnc: encrypt(password),
      voicemailPinEnc: encrypt(pin),
      voicemailEnabled: body.voicemailEnabled ?? true,
      voicemailEmail: body.voicemailEmail ?? null,
      callerIdName: body.callerIdName ?? null,
      callerIdNumber: body.callerIdNumber ?? null,
      codecPrefs: body.codecPrefs ?? null,
      maxConcurrentCalls: body.maxConcurrentCalls ?? null,
      deviceMac: body.deviceMac ?? null,
    })
    .returning();

  if (!row) return c.json({ error: "Insert failed" }, 500);

  await syncSubscriber(row, tenant.sipDomain, password);
  await cacheExtension(row.id);
  await recordAudit(c, { action: "create", entityType: "extension", entityId: row.id, after: row });

  // The only time the plaintext secrets are returned: the operator has to configure the handset
  // with the password and tell the user their PIN, and neither is recoverable afterwards.
  return c.json({ ...present(row), sipPassword: password, voicemailPin: pin }, 201);
});

extensions.patch("/:id", async (c) => {
  const organizationId = c.get("organizationId");
  const id = c.req.param("id");

  const before = await db.query.extension.findFirst({
    where: and(eq(extension.id, id), eq(extension.organizationId, organizationId)),
  });
  if (!before) return c.json({ error: "Not found" }, 404);

  const body = await c.req.json<Partial<{
    displayName: string;
    sipPassword: string;
    voicemailEnabled: boolean;
    /** Pass an empty string to have a new one generated - the reset-my-PIN case. */
    voicemailPin: string;
    voicemailEmail: string | null;
    callerIdName: string | null;
    callerIdNumber: string | null;
    codecPrefs: string | null;
    maxConcurrentCalls: number | null;
    directoryCacheMs: number | null;
    deviceMac: string | null;
    enabled: boolean;
  }>>();

  const patch: Partial<typeof extension.$inferInsert> = {};
  if (body.displayName !== undefined) patch.displayName = body.displayName;
  if (body.voicemailEnabled !== undefined) patch.voicemailEnabled = body.voicemailEnabled;
  if (body.voicemailEmail !== undefined) patch.voicemailEmail = body.voicemailEmail;
  if (body.callerIdName !== undefined) patch.callerIdName = body.callerIdName;
  if (body.callerIdNumber !== undefined) patch.callerIdNumber = body.callerIdNumber;
  if (body.codecPrefs !== undefined) patch.codecPrefs = body.codecPrefs;
  if (body.maxConcurrentCalls !== undefined) patch.maxConcurrentCalls = body.maxConcurrentCalls;
  if (body.directoryCacheMs !== undefined) patch.directoryCacheMs = body.directoryCacheMs;
  if (body.deviceMac !== undefined) patch.deviceMac = body.deviceMac;
  if (body.enabled !== undefined) patch.enabled = body.enabled;
  if (body.sipPassword !== undefined) patch.sipPasswordEnc = encrypt(body.sipPassword);

  let newPin: string | undefined;
  if (body.voicemailPin !== undefined) {
    if (body.voicemailPin !== "" && !/^\d{4,10}$/.test(body.voicemailPin)) {
      return c.json({ error: "voicemailPin must be 4 to 10 digits" }, 400);
    }
    newPin = body.voicemailPin === "" ? generateVoicemailPin() : body.voicemailPin;
    patch.voicemailPinEnc = encrypt(newPin);
  }

  const [row] = await db
    .update(extension)
    .set(patch)
    .where(and(eq(extension.id, id), eq(extension.organizationId, organizationId)))
    .returning();
  if (!row) return c.json({ error: "Update failed" }, 500);

  const tenant = await db.query.tenantSettings.findFirst({
    where: eq(tenantSettings.organizationId, organizationId),
  });
  if (tenant) {
    if (body.sipPassword !== undefined) {
      await syncSubscriber(row, tenant.sipDomain, body.sipPassword);
    }
    await cacheExtension(row.id);
  }
  await recordAudit(c, {
    action: "update",
    entityType: "extension",
    entityId: id,
    before,
    after: row,
  });

  // Returned only on the request that set it, mirroring the create route.
  return c.json(newPin ? { ...present(row), voicemailPin: newPin } : present(row));
});

extensions.delete("/:id", async (c) => {
  const organizationId = c.get("organizationId");
  const id = c.req.param("id");

  const before = await db.query.extension.findFirst({
    where: and(eq(extension.id, id), eq(extension.organizationId, organizationId)),
  });
  if (!before) return c.json({ error: "Not found" }, 404);

  const tenant = await db.query.tenantSettings.findFirst({
    where: eq(tenantSettings.organizationId, organizationId),
  });

  await db
    .delete(extension)
    .where(and(eq(extension.id, id), eq(extension.organizationId, organizationId)));

  // Remove the registration credential before dropping the cache, so a race cannot leave a
  // deleted extension briefly able to register.
  if (tenant) {
    await removeSubscriber(before.number, tenant.sipDomain);
    await invalidateExtension(organizationId, before.number, tenant.sipDomain);
  }
  await recordAudit(c, { action: "delete", entityType: "extension", entityId: id, before });

  return c.body(null, 204);
});
