/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AingaranRouteImport } from "./routes/aingaran"
import { Route as HomeRouteImport } from "./routes/telus"

const AingaranRoute = AingaranRouteImport.update({
  id: "/Aingaran",
  path: "/Aingaran",
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: "/Home",
  path: "/Home",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/Aingaran": typeof AingaranRoute
  "/Home": typeof HomeRoute
}
export interface FileRoutesByTo {
  "/Aingaran": typeof AingaranRoute
  "/Home": typeof HomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/Aingaran": typeof AingaranRoute
  "/Home": typeof HomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: "/Aingaran" | "/Home"
  fileRoutesByTo: FileRoutesByTo
  to: "/Aingaran" | "/Home"
  id: "__root__" | "/Aingaran" | "/Home"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AingaranRoute: typeof AingaranRoute
  HomeRoute: typeof HomeRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/Aingaran": {
      id: "/Aingaran"
      path: "/Aingaran"
      fullPath: "/Aingaran"
      preLoaderRoute: typeof AingaranRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/Home": {
      id: "/Home"
      path: "/Home"
      fullPath: "/Home"
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AingaranRoute: AingaranRoute,
  HomeRoute: HomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
