/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppCallFlowsRouteImport } from './routes/_app/call-flows'
import { Route as AppCallsRouteImport } from './routes/_app/calls'
import { Route as AppExtensionsRouteImport } from './routes/_app/extensions'
import { Route as AppRoutingRouteImport } from './routes/_app/routing'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppTrunksRouteImport } from './routes/_app/trunks'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppCallFlowsRoute = AppCallFlowsRouteImport.update({
  id: '/call-flows',
  path: '/call-flows',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppExtensionsRoute = AppExtensionsRouteImport.update({
  id: '/extensions',
  path: '/extensions',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutingRoute = AppRoutingRouteImport.update({
  id: '/routing',
  path: '/routing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppTrunksRoute = AppTrunksRouteImport.update({
  id: '/trunks',
  path: '/trunks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/call-flows': typeof AppCallFlowsRoute
  '/calls': typeof AppCallsRoute
  '/extensions': typeof AppExtensionsRoute
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/trunks': typeof AppTrunksRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/call-flows': typeof AppCallFlowsRoute
  '/calls': typeof AppCallsRoute
  '/extensions': typeof AppExtensionsRoute
  '/routing': typeof AppRoutingRoute
  '/settings': typeof AppSettingsRoute
  '/trunks': typeof AppTrunksRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/call-flows': typeof AppCallFlowsRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/extensions': typeof AppExtensionsRoute
  '/_app/routing': typeof AppRoutingRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/trunks': typeof AppTrunksRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/call-flows'
    | '/calls'
    | '/extensions'
    | '/routing'
    | '/settings'
    | '/trunks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/call-flows'
    | '/calls'
    | '/extensions'
    | '/routing'
    | '/settings'
    | '/trunks'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/call-flows'
    | '/_app/calls'
    | '/_app/extensions'
    | '/_app/routing'
    | '/_app/settings'
    | '/_app/trunks'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/call-flows': {
      id: '/_app/call-flows'
      path: '/call-flows'
      fullPath: '/call-flows'
      preLoaderRoute: typeof AppCallFlowsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/extensions': {
      id: '/_app/extensions'
      path: '/extensions'
      fullPath: '/extensions'
      preLoaderRoute: typeof AppExtensionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routing': {
      id: '/_app/routing'
      path: '/routing'
      fullPath: '/routing'
      preLoaderRoute: typeof AppRoutingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/trunks': {
      id: '/_app/trunks'
      path: '/trunks'
      fullPath: '/trunks'
      preLoaderRoute: typeof AppTrunksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCallFlowsRoute: typeof AppCallFlowsRoute
  AppCallsRoute: typeof AppCallsRoute
  AppExtensionsRoute: typeof AppExtensionsRoute
  AppRoutingRoute: typeof AppRoutingRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTrunksRoute: typeof AppTrunksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCallFlowsRoute: AppCallFlowsRoute,
  AppCallsRoute: AppCallsRoute,
  AppExtensionsRoute: AppExtensionsRoute,
  AppRoutingRoute: AppRoutingRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTrunksRoute: AppTrunksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
