#!/usr/bin/env bash
### Build the React admin portal and publish it for nginx to serve.
###
### The portal is a static bundle - Vite compiles it once here and nginx serves the files
### directly. There is no Node process for the frontend at runtime; it talks to the Hono API
### over /api.
set -euo pipefail
. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/../lib/common.sh"

require_root
load_config

SRC="$REPO_DIR/portal/web"
WEB_ROOT="${WEB_ROOT:-/var/www/voip-portal}"
BUILD_USER="${API_USER:-voipapi}"

[ -d "$SRC" ] || die "No portal source at $SRC."
command -v bun >/dev/null || die "Bun is not installed - run 40-bun.sh first."

### --- Build ---------------------------------------------------------------------------------

### Build in a scratch copy owned by an unprivileged user. Running a build as root means every
### postinstall script in the dependency tree runs as root too.
BUILD_DIR="/var/tmp/voip-portal-build"
rm -rf "$BUILD_DIR"
install -d -m 0755 -o "$BUILD_USER" -g "$BUILD_USER" "$BUILD_DIR"

rsync -a --exclude 'node_modules' --exclude 'dist' "$SRC/" "$BUILD_DIR/"
chown -R "$BUILD_USER:$BUILD_USER" "$BUILD_DIR"

### The API is same-origin behind nginx, so a relative base keeps the bundle portable between
### environments - no rebuild needed to change hostname.
write_file "$BUILD_DIR/.env.production" 0644 "$BUILD_USER:$BUILD_USER" <<EOF || true
# Generated by the VoIP PBX installer.
VITE_API_BASE=/api
VITE_PBX_FQDN=${PBX_FQDN}
VITE_SIP_DOMAIN=${PBX_SIP_DOMAIN}
EOF

info "Installing portal dependencies"
su -s /bin/bash -c "cd '$BUILD_DIR' && bun install --frozen-lockfile" "$BUILD_USER" \
  || su -s /bin/bash -c "cd '$BUILD_DIR' && bun install" "$BUILD_USER" \
  || die "bun install failed for the portal."

info "Building the portal"
su -s /bin/bash -c "cd '$BUILD_DIR' && bun run build" "$BUILD_USER" \
  || die "Portal build failed."

[ -d "$BUILD_DIR/dist" ] || die "Build produced no dist/ directory."

### --- Publish -------------------------------------------------------------------------------

### Swap the built output in atomically. A plain rsync into the live root would serve a
### half-updated bundle - index.html referencing hashed assets that are not there yet.
install -d -m 0755 "$(dirname "$WEB_ROOT")"
rm -rf "${WEB_ROOT}.new"
cp -a "$BUILD_DIR/dist" "${WEB_ROOT}.new"
chown -R root:www-data "${WEB_ROOT}.new"
chmod -R u=rwX,g=rX,o= "${WEB_ROOT}.new"

if [ -d "$WEB_ROOT" ]; then
  rm -rf "${WEB_ROOT}.old"
  mv "$WEB_ROOT" "${WEB_ROOT}.old"
fi
mv "${WEB_ROOT}.new" "$WEB_ROOT"
rm -rf "${WEB_ROOT}.old" "$BUILD_DIR"

files="$(find "$WEB_ROOT" -type f | wc -l)"
size="$(du -sh "$WEB_ROOT" | cut -f1)"
ok "Portal published to $WEB_ROOT ($files files, $size)"

if systemctl is-active --quiet nginx; then
  systemctl reload nginx
  ok "nginx reloaded"
else
  warn "nginx is not running - run 42-nginx.sh to serve the portal."
fi
